version: "3.1"

services:
  mongo_db:
    image: mongo
    container_name: mongo_db
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017

  redis_db:
    image: redis
    container_name: redis_db
    command: redis-server --requirepass secret
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
